# fly.toml app configuration file generated for surf-forecast-bot on 2024-03-30T16:57:24-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'surf-forecast-bot'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
